# -*- coding: utf-8 -*-
"""GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYPSTv8G4xIg89jBIwMC5avhjnrIFqJS
"""

# Import libraries (if you've restarted the notebook)
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

# Load the CIFAR-10 dataset
(train_images, train_labels), (_, _) = tf.keras.datasets.cifar10.load_data()

# Preprocess the data for a 32x32 image
train_images = train_images.reshape(train_images.shape[0], 32, 32, 3).astype('float32')
# Normalize the images to [-1, 1]
train_images = (train_images - 127.5) / 127.5

# Define buffer and batch sizes
BUFFER_SIZE = 50000
BATCH_SIZE = 256

# Create the Dataset object
train_dataset = tf.data.Dataset.from_tensor_slices(train_images).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

def make_discriminator_model():
    model = tf.keras.Sequential()
    # Input shape is now 32x32x3
    model.add(layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same',
                                     input_shape=[32, 32, 3])) #<-- CHANGE
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    # We add an extra layer to get down to a smaller size
    model.add(layers.Conv2D(256, (5, 5), strides=(2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(1))

    return model

discriminator = make_discriminator_model()
discriminator.summary()

def make_generator_model():
    model = tf.keras.Sequential()
    # Start with a Dense layer that can be reshaped to a 4x4 block
    model.add(layers.Dense(4*4*256, use_bias=False, input_shape=(100,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Reshape((4, 4, 256))) # Reshape to a 4x4 starting point

    # Upsample to 8x8
    model.add(layers.Conv2DTranspose(128, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    # Upsample to 16x16
    model.add(layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    # Final upsample to 32x32.
    # The output has 3 channels for RGB color and uses tanh.
    model.add(layers.Conv2DTranspose(3, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh')) #<-- CHANGE

    return model

generator = make_generator_model()
generator.summary()

# Create a small batch of random noise (1 image in this case)
noise = tf.random.normal([1, 100])
# Pass the noise through the generator
generated_image = generator(noise, training=False)

# Display the image
plt.imshow(generated_image[0, :, :, 0], cmap='gray')


# This is a helper function that helps us calculate the loss.
# We'll be comparing the discriminator's predictions against a target of all ones for real images,
# and all zeros for fake images.
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

# -------------------------------------
# 1. DISCRIMINATOR'S LOSS
# How well does the detective tell real from fake?
# -------------------------------------
def discriminator_loss(real_output, fake_output):
    # The discriminator's loss has two parts:
    # a) How well it classified the REAL images. We want it to predict '1' (real) for these.
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)

    # b) How well it classified the FAKE images. We want it to predict '0' (fake) for these.
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)

    # The total loss is the sum of these two.
    total_loss = real_loss + fake_loss
    return total_loss

# -------------------------------------
# 2. GENERATOR'S LOSS
# How well did the artist fool the detective?
# -------------------------------------
def generator_loss(fake_output):
    # The generator wins if the discriminator classified its fake image as REAL (a '1').
    # So, its loss is how far the discriminator's output (fake_output) was from '1'.
    return cross_entropy(tf.ones_like(fake_output), fake_output)

# -------------------------------------
# 3. THE OPTIMIZERS
# These will apply the gradients to update the network weights.
# -------------------------------------
generator_optimizer = tf.keras.optimizers.Adam(1e-4)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-4)


import time
import os # We'll use this to save our checkpoints

# Define the number of training epochs and the noise dimension
EPOCHS = 250 # Start with 50. You can increase this later for better results.
noise_dim = 100
num_examples_to_generate = 16

# We will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF
seed = tf.random.normal([num_examples_to_generate, noise_dim])

# The @tf.function decorator compiles this function into a high-performance TensorFlow graph.
# This makes it run much, much faster.
@tf.function
def train_step(images):
    # Generate noise for the generator
    noise = tf.random.normal([BATCH_SIZE, noise_dim])

    # 'tf.GradientTape' is the magic recorder. It records all operations
    # to automatically calculate the gradients later. We need two tapes,
    # one for each model.
    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        # 1. The Generator creates fakes
        generated_images = generator(noise, training=True)

        # 2. The Discriminator evaluates both real and fake images
        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        # 3. We calculate the loss for each model using the functions we defined earlier
        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)

    # 4. Calculate the gradients (the direction of "improvement") for each model
    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    # 5. Apply the gradients to the models' parameters, making them learn
    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

# Create a helper function to generate and save images
def generate_and_save_images(model, epoch, test_input):
  predictions = model(test_input, training=False)
  fig = plt.figure(figsize=(4, 4))

  for i in range(predictions.shape[0]):
      plt.subplot(4, 4, i+1)
      # To display, we scale the pixel values from [-1, 1] to [0, 1]
      plt.imshow((predictions[i, :, :, :] + 1) / 2) #<-- CHANGE
      plt.axis('off')

  plt.savefig('image_at_epoch_{:04d}.png'.format(epoch))
  plt.show()

# Define the training function that will loop over epochs and steps
def train(dataset, epochs):
  for epoch in range(epochs):
    start = time.time()

    for image_batch in dataset:
      train_step(image_batch)

    # After each epoch, produce a plot of our 16 images to see progress
    print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))
    generate_and_save_images(generator, epoch + 1, seed)

  # Generate after the final epoch
  generate_and_save_images(generator, epochs, seed)


# And... ACTION!
train(train_dataset, EPOCHS)