# -*- coding: utf-8 -*-
"""GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYPSTv8G4xIg89jBIwMC5avhjnrIFqJS
"""

# Import necessary libraries
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

# Load the MNIST dataset
(train_images, train_labels), (_, _) = tf.keras.datasets.fashion_mnist.load_data()

# Preprocess the data
# We are reshaping the images to include a channel dimension, which CNNs expect.
train_images = train_images.reshape(train_images.shape[0], 28, 28, 1).astype('float32')
# We are normalizing the pixel values from [0, 255] to [-1, 1].
# This helps the GAN train more stably.
train_images = (train_images - 127.5) / 127.5

# Define the buffer and batch sizes
BUFFER_SIZE = 60000
BATCH_SIZE = 256

# Create a tf.data.Dataset object to efficiently handle the data
train_dataset = tf.data.Dataset.from_tensor_slices(train_images).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

def make_discriminator_model():
    model = tf.keras.Sequential()
    # Input shape is 28x28 with 1 color channel
    model.add(layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same',
                                     input_shape=[28, 28, 1]))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(1)) # No sigmoid activation here, we'll apply it in the loss function

    return model

discriminator = make_discriminator_model()
discriminator.summary()

def make_generator_model():
    model = tf.keras.Sequential()
    # Start with a Dense layer that takes our random noise vector (size 100) as input
    model.add(layers.Dense(7*7*256, use_bias=False, input_shape=(100,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    # Reshape the 1D vector into a 3D block (7x7 with 256 feature maps)
    model.add(layers.Reshape((7, 7, 256)))
    assert model.output_shape == (None, 7, 7, 256) # Note: None is the batch size

    # First upsampling layer: from 7x7 to 14x14
    model.add(layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 7, 7, 128)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    # Second upsampling layer: from 7x7 to 14x14
    model.add(layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 14, 14, 64)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    # Final upsampling layer to get our 28x28 image
    # Note the 'tanh' activation function at the end. This ensures the output pixel values
    # are between -1 and 1, just like our preprocessed real images.
    model.add(layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh'))
    assert model.output_shape == (None, 28, 28, 1)

    return model

generator = make_generator_model()
generator.summary()

# Create a small batch of random noise (1 image in this case)
noise = tf.random.normal([1, 100])
# Pass the noise through the generator
generated_image = generator(noise, training=False)

# Display the image
plt.imshow(generated_image[0, :, :, 0], cmap='gray')


# This is a helper function that helps us calculate the loss.
# We'll be comparing the discriminator's predictions against a target of all ones for real images,
# and all zeros for fake images.
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

# -------------------------------------
# 1. DISCRIMINATOR'S LOSS
# How well does the detective tell real from fake?
# -------------------------------------
def discriminator_loss(real_output, fake_output):
    # The discriminator's loss has two parts:
    # a) How well it classified the REAL images. We want it to predict '1' (real) for these.
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)

    # b) How well it classified the FAKE images. We want it to predict '0' (fake) for these.
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)

    # The total loss is the sum of these two.
    total_loss = real_loss + fake_loss
    return total_loss

# -------------------------------------
# 2. GENERATOR'S LOSS
# How well did the artist fool the detective?
# -------------------------------------
def generator_loss(fake_output):
    # The generator wins if the discriminator classified its fake image as REAL (a '1').
    # So, its loss is how far the discriminator's output (fake_output) was from '1'.
    return cross_entropy(tf.ones_like(fake_output), fake_output)

# -------------------------------------
# 3. THE OPTIMIZERS
# These will apply the gradients to update the network weights.
# -------------------------------------
generator_optimizer = tf.keras.optimizers.Adam(1e-4)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-4)


import time
import os # We'll use this to save our checkpoints

# Define the number of training epochs and the noise dimension
EPOCHS = 60 # Start with 50. You can increase this later for better results.
noise_dim = 100
num_examples_to_generate = 16

# We will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF
seed = tf.random.normal([num_examples_to_generate, noise_dim])

# The @tf.function decorator compiles this function into a high-performance TensorFlow graph.
# This makes it run much, much faster.
@tf.function
def train_step(images):
    # Generate noise for the generator
    noise = tf.random.normal([BATCH_SIZE, noise_dim])

    # 'tf.GradientTape' is the magic recorder. It records all operations
    # to automatically calculate the gradients later. We need two tapes,
    # one for each model.
    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        # 1. The Generator creates fakes
        generated_images = generator(noise, training=True)

        # 2. The Discriminator evaluates both real and fake images
        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        # 3. We calculate the loss for each model using the functions we defined earlier
        gen_loss = generator_loss(fake_output)
        disc_loss = discriminator_loss(real_output, fake_output)

    # 4. Calculate the gradients (the direction of "improvement") for each model
    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    # 5. Apply the gradients to the models' parameters, making them learn
    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

# Create a helper function to generate and save images
def generate_and_save_images(model, epoch, test_input):
  # Notice `training` is set to False.
  # This is so all layers run in inference mode (batchnorm).
  predictions = model(test_input, training=False)

  fig = plt.figure(figsize=(4, 4))

  for i in range(predictions.shape[0]):
      plt.subplot(4, 4, i+1)
      # We need to scale the pixel values back to [0, 1] to display them
      plt.imshow(predictions[i, :, :, 0] * 127.5 + 127.5, cmap='gray')
      plt.axis('off')

  plt.savefig('image_at_epoch_{:04d}.png'.format(epoch))
  plt.show()

# Define the training function that will loop over epochs and steps
def train(dataset, epochs):
  for epoch in range(epochs):
    start = time.time()

    for image_batch in dataset:
      train_step(image_batch)

    # After each epoch, produce a plot of our 16 images to see progress
    print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))
    generate_and_save_images(generator, epoch + 1, seed)

  # Generate after the final epoch
  generate_and_save_images(generator, epochs, seed)


# And... ACTION!
train(train_dataset, EPOCHS)